/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

import javax.swing.JInternalFrame;
import javax.swing.JFrame;

public class FrmMenuPrincipal extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FrmMenuPrincipal.class.getName());

    /**
     * Creates new form FrmMenuPrincipal
     */
    public FrmMenuPrincipal() {
        initComponents();
        this.setExtendedState(MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnClientes = new javax.swing.JButton();
        btnEmpleados = new javax.swing.JButton();
        btnProductos = new javax.swing.JButton();
        btnFacturacion = new javax.swing.JButton();
        btnPago = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sistema de Ventas");

        btnClientes.setText("Clientes");
        btnClientes.addActionListener(this::btnClientesActionPerformed);

        btnEmpleados.setText("Empleados");
        btnEmpleados.addActionListener(this::btnEmpleadosActionPerformed);

        btnProductos.setText("Productos");
        btnProductos.addActionListener(this::btnProductosActionPerformed);

        btnFacturacion.setText("Facturación");
        btnFacturacion.addActionListener(this::btnFacturacionActionPerformed);

        btnPago.setText("Pagos");
        btnPago.addActionListener(this::btnPagoActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(145, 145, 145)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(btnPago)
                        .addComponent(btnFacturacion)
                        .addComponent(btnProductos)
                        .addComponent(btnClientes))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnEmpleados)
                        .addGap(6, 6, 6)))
                .addGap(150, 150, 150))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(btnClientes)
                .addGap(18, 18, 18)
                .addComponent(btnEmpleados)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnProductos)
                .addGap(15, 15, 15)
                .addComponent(btnFacturacion)
                .addGap(15, 15, 15)
                .addComponent(btnPago)
                .addGap(0, 33, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnClientesActionPerformed(java.awt.event.ActionEvent evt) {
        abrirVentana("Vista.FrmClientes", "Clientes");
    }

    private void btnEmpleadosActionPerformed(java.awt.event.ActionEvent evt) {
        abrirVentana("Vista.FrmEmpleados", "Empleados");
    }

    private void btnProductosActionPerformed(java.awt.event.ActionEvent evt) {
        abrirVentana("Vista.FrmProductos", "Productos");
    }

    private void btnFacturacionActionPerformed(java.awt.event.ActionEvent evt) {
        abrirVentana("Vista.FrmFacturacion", "Facturación");
    }

    private void btnPagoActionPerformed(java.awt.event.ActionEvent evt) {
        abrirVentana("Vista.FrmPago", "Pagos");
    }

    /**
     * Abre una pantalla del sistema por su nombre de clase completo.
     * Se usa reflexión para que este menú funcione aunque la pantalla
     * de un compañero todavía no exista o esté en desarrollo.
     */
    private void abrirVentana(String claseFQN, String nombreModulo) {
        try {
            Class<?> clazz = Class.forName(claseFQN);
            javax.swing.JFrame frame = (javax.swing.JFrame) clazz.getDeclaredConstructor().newInstance();
            frame.setLocationRelativeTo(this);
            frame.setVisible(true);
        } catch (ReflectiveOperationException | ClassCastException ex) {
            logger.log(java.util.logging.Level.WARNING, "No se pudo abrir el módulo " + nombreModulo, ex);
            javax.swing.JOptionPane.showMessageDialog(this,
                    "El módulo de " + nombreModulo + " aún no está disponible.",
                    "Sistema de Ventas",
                    javax.swing.JOptionPane.INFORMATION_MESSAGE);
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FrmMenuPrincipal().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClientes;
    private javax.swing.JButton btnEmpleados;
    private javax.swing.JButton btnFacturacion;
    private javax.swing.JButton btnPago;
    private javax.swing.JButton btnProductos;
    // End of variables declaration//GEN-END:variables
}
